#pragma once

enum eEVENT_TYPE
{
    EVT_INVALID,
    EVT_STATE_ENTRY,
    EVT_STATE_EXIT,
    EVT_STATE_CHANGED,
    EVT_INP_INCREMENT,
    EVT_INP_DECREMENT,
    EVT_INP_PRESSED,
    EVT_INP_RELEASED,
    EVT_INP_LONG_PRESS,
    EVT_INP_LONG_LONG_PRESS
};
